### ISSUE TITLE
How to test the components?

### ISSUE THREAD

**Issue by call0fcode** [matlinski/components#1]
Hey! I wanted to test the things you've made until now in order to see how easy it is to put some nice stuff on the browser with a couple of lines of code but I don't know where & how to deal with it.

Have you got already some docs or something similar? You'll definitely need one someday ...

**Comment by matlinski** [comment]
Hello Juan how nice of you :) I test all of the components on the page.php where you can start filling up the body tag with the components. If you would like to make a completely new page it's as easy as create a new file and requiring once library.php in the head tag of your page and your good to go. Can't wait to see your compositions mate!
